---
# tasks file for clickhouse
- name: 'Include OS Family Specific Variables'
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}.yml"
        - 'empty.yml'
      paths:
        - 'vars'
  tags: [always]

- include_tasks: precheck.yml
  tags: [always]

- include_tasks: params.yml
  tags: [always]

- include_tasks:
    file: "{{ lookup('first_found', params) }}"
    apply:
      tags: [install]
  vars:
    params:
      files:
        - "install/{{ ansible_pkg_mgr }}.yml"
        - 'empty.yml'
  tags: [install]
  when: not clickhouse_remove|bool

- include_tasks:
    file: configure/sys.yml
    apply:
      tags: [config, config_sys]
  tags: [config, config_sys]
  when: not clickhouse_remove|bool

- include_tasks:
    file: service.yml
    apply:
      tags: [install]
  tags: [install]

- name: "Notify Handlers Now"
  tags: [always]
  meta: flush_handlers

- name: "Wait for Clickhouse Server to Become Ready"
  wait_for:
    port: "{{ clickhouse_tcp_secure_port | default(clickhouse_tcp_port) }}"
    delay: "{{ clickhouse_ready_delay }}"
  retries: "{{ clickhouse_ready_retries }}"
  tags: [config, install]
  when: not clickhouse_remove|bool

- include_tasks:
    file: configure_sql/settings-profiles.yml
    apply:
      tags: [config, config_settings_profiles]
  tags: [config, config_settings_profiles]
  when: not clickhouse_remove|bool

- include_tasks:
    file: configure_sql/roles.yml
    apply:
      tags: [config, config_roles]
  tags: [config, config_roles]
  when: not clickhouse_remove|bool

- include_tasks:
    file: configure_sql/quotas.yml
    apply:
      tags: [config, config_quotas]
  tags: [config, config_quotas]
  when: not clickhouse_remove|bool

- include_tasks:
    file: configure_sql/users.yml
    apply:
      tags: [config, config_users]
  tags: [config, config_users]
  when: not clickhouse_remove|bool

- include_tasks:
    file: configure_sql/db.yml
    apply:
      tags: [config, config_db]
  tags: [config, config_db]
  when: not clickhouse_remove|bool

- include_tasks:
    file: configure_sql/perms_and_privs.yml
    apply:
      tags: [config, config_grants]
  tags: [config, config_grants]
  when: not clickhouse_remove|bool

- include_tasks:
    file: configure/dict.yml
    apply:
      tags: [config, config_dict]
  tags: [config, config_dict]
  when: not clickhouse_remove|bool

- include_tasks:
    file: remove.yml
    apply:
      tags: [remove]
  tags: [remove]
  when: clickhouse_remove|bool
