---
- name: CLICKHOUSE | List users (SQL-driven)
  ansible.builtin.command: |
    {{ clickhouse_connection_string }}
    -q
    "SELECT name FROM system.users WHERE storage == 'local_directory';"
  changed_when: False
  register: clickhouse_existing_sql_users
  tags: [config_settings_users]

- name: CLICKHOUSE | Drop users (SQL-driven)
  ansible.builtin.command: |
    {{ clickhouse_connection_string }}
    -q
    "DROP USER IF EXISTS '{{ item }}';"
  with_items: "{{ clickhouse_existing_sql_users.stdout_lines }}"
  when:
    - clickhouse_existing_sql_users is defined
    - item not in clickhouse_users_custom_sql | map(attribute='name') | list
  register: drop_users
  changed_when: drop_users.rc != 0
  tags: [config_settings_users]

- name: CLICKHOUSE | Add users (SQL-driven)
  ansible.builtin.command: |
    {{ clickhouse_connection_string }}
    -q
    {{ lookup('template', 'DDL/USER.j2') | quote }};
  with_items: "{{ clickhouse_users_custom_sql }}"
  when:
    - clickhouse_users_custom_sql is defined
    - item.name not in clickhouse_existing_sql_users.stdout_lines
  register: add_users
  changed_when: add_users.rc != 0
  tags: [config_settings_users]
