---
- name: Config | Create dictionaries directory
  file:
    path: "{{ clickhouse_path_configdir }}/dicts.d"
    owner: "{{ clickhouse_user | default('clickhouse') }}"
    group: "{{ clickhouse_group | default('clickhouse') }}"
    mode: "ug=rwx,o-rwx"
    state: directory
  become: true
  when: clickhouse_dicts|length>0

- name: Config | Generate dictionary config
  template:
    src: dicts.j2
    dest: "{{ clickhouse_path_configdir }}/dicts.d/auto_dictionary.xml"
    owner: "{{ clickhouse_user | default('clickhouse') }}"
    group: "{{ clickhouse_group | default('clickhouse') }}"
    mode: "ug=rw,o-rwx"
  become: true
  when: clickhouse_dicts|length>0
